config/routes.rb
Rails.application.routes.draw do

  get 'downgrade/create'
  get 'downgrade/new'
  get 'charges/new'
  get 'charges/create'
  
  resources :wikis do
    resources :collaborators, only: [:new, :create, :destroy]
  end
  
  devise_for :users
  get 'about' => 'welcome#about'
  get 'welcome/about'
  
  resources :charges, only: [:new, :create]

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/models/install.rb
class Install < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord


    # Include default devise modules. Others available are:
  #  :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  after_initialize {self.role ||= :standard}

  has_many :wikis, dependent: :destroy
  has_many :collaborators, dependent: :destroy


  enum role: [:standard, :premium, :admin]

end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include Pundit
  protect_from_forgery

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    def new
        @amount = 15_00
        @stripe_btn_data = {
            key: "#{ Rails.configuration.stripe[:publishable_key] }",
            description: "MADE Membership - #{current_user.email}",
            amount: @amount
        }
    end
  
          

    def create
  
        @amount = 15_00
    # Creates a Stripe Customer object, for associating
    # with the charge
        customer = Stripe::Customer.create(
            email: current_user.email,
            card: params[:stripeToken]
        )
 
        # Where the real magic happens
        charge = Stripe::Charge.create(
            customer: customer.id, 
            amount: @amount,
            description: "MADE Premier Membership - #{current_user.email}",
            currency: 'usd'
        )
 
        current_user.update_attribute(:role, 'premium')

    
        flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
   
        redirect_to root_path
 
   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   # This `rescue block` catches and displays those errors.
        rescue Stripe::CardError => e
        flash[:alert] = e.message
        redirect_to new_charge_path
    end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
 
    def new
        @collaborator = @wiki.collaborators.new
    end    
    
    def create
        @collaborator_user = User.find_by_email(params[:collaborator])
        @wiki = Wiki.find(params[:wiki_id])
        @user = current_user
        
        if @collaborator_user
            if @wiki.collaborators.include?(@collaborator_user) || @collaborator_user == @user 
                flash[:notice] = "#{@collaborator_user.email} is already a collaborator."
                redirect_to edit_wiki_path(@wiki)
            else
                @collaborator = @wiki.collaborators.new(wiki_id: @wiki.id, user_id: @collaborator_user.id)
                if @collaborator.save
                    flash[:notice] =  "#{@collaborator_user.email} was added as a collaborator."
                    puts @wiki.collaborators
                    redirect_to @wiki
                else 
                    flash[:alert] = "There was an error adding this collaborator. Please try again."
                    redirect_to edit_wiki_path(@wiki)
                end    
            end
        else
            flash[:notice] = "User is not in the system yet."
        end    
    end    
    
    def destroy
        @wiki = Wiki.find(params[:wiki_id])
        @collaborator_user = @wiki.collaborators.find(params[:id])
        
        if @collaborator_user.destroy
            flash[:notice] = "Collaborator has been successfully removed. "
            redirect_to @wiki
        else
            flash.now[:alert] = "There was an error removing this collaborator."
        redirect_to @wiki
        end
    end
    
    
    
end

app/controllers/downgrade_controller.rb
class DowngradeController < ApplicationController
  def create
    
    
    current_user.update_attribute(:role, 'standard')
    current_user.wikis.update_all(private: false)
    flash[:notice] = "You have successfully downgraded your account."
        
    redirect_to root_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController




  def index
    @wikis = Wiki.all

  end

  def show
     @wiki = Wiki.find(params[:id])
     authorize @wiki
  end

  def new
      @wiki = Wiki.new
      
  end

  def create
      @wiki = current_user.wikis.new(wiki_params)
      authorize @wiki

     if @wiki.save

       flash[:notice] = "Post was saved."
       redirect_to wikis_path

     else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end



  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end

  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    authorize @wiki

      if @wiki.save
        flash[:notice] = "post was updated"
        redirect_to @wiki
      else
        flash.now[:alert] = 'there was an error saving the post, please try again'
        render :edit
      end
    end

    def destroy
      @wiki = Wiki.find(params[:id])
      authorize @wiki

      if @wiki.destroy
        flash[:notice] = "#{@wiki.title} was deleted successfully."
        redirect_to wikis_path
      else
        flash.now[:alert] = "There was an error deleting the wiki"
        render :show
      end

    end

  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private)
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def markdown(text)
    
    renderer = Redcarpet::Render::HTML.new()
    markdown = Redcarpet::Markdown.new(renderer)
    
    markdown.render(text).html_safe
  
  end  


  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade in") do
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message
            end)
    end
    nil
  end

end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/downgrade_helper.rb
module DowngradeHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/create.html.erb
<h1>Charges#create</h1>
<p>Find me in app/views/charges/create.html.erb</p>

app/views/charges/new.html.erb
<% if @current_user.standard? %>
    <%= form_tag charges_path do %>
        <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
    <% end %>
<%else%>


<%end%>

app/views/collaborators/_collaborators.html.erb
<div class="form-group">
    <div class="col-md-4">
    
         <% if current_user.premium? && current_user == @wiki.user || current_user.admin? %>
              <div class="col-md-8">
                <h3>Add Collaborators</h3>

                    <%= form_for [@wiki, Collaborator.new] do |c| %>
                        <%= email_field_tag :collaborator %>
                        <%= c.submit "Add collaborator", class: 'btn btn-primary' %>
                    <% end %>

                <h3>Manage Collaborators</h3>

                    <% @wiki.collaborators.each do |c| %>
                      <% user = User.find(c.user_id) %>
                      <%= user.email %>
                      <%= link_to "Delete", wiki_collaborator_path(@wiki, c), class: 'btn btn-danger', method: :delete%>
                    <% end %>
              </div>
          <% end %>
    </div>      
</div>

app/views/downgrade/create.html.erb
<h1>Downgrade#create</h1>
<p>Find me in app/views/downgrade/create.html.erb</p>

app/views/downgrade/new.html.erb
<h4>Would you like to downgrade your account back to standard?</h4>
<p>Remember, you will have to pay another $15 to get premium features back on your account, and your private wikis will become public.</p>
<%= link_to "Downgrade Your Account", downgrade_create_path, method: :get, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to downgrade?'} %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lizapedia</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script>blocmetrics.report('home page loaded');</script>
  </head>

  <body>
    <div class= "container">
        <ul class="nav nav-tabs">
          <li class="nav-item">
            <%= link_to "Home", root_path, :class => 'nav-link' %>
          </li>
          <li class= "nav-item">
            <%= link_to " About", about_path, :class => 'nav-link' %>
          </li>
          <li class= "nav-item">
            <%= link_to "Wikis", wikis_path, :class => 'nav-link'  %>
          </li>

        <div class="pull-right">
            <% if user_signed_in? %>
              <li class="pull-right"> Signed in as: <strong><%= current_user.email %></strong> </li> </br>
              <li class="pull-right"><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> </li> </br>
              <li class="pull-right"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> </li>
            <% else %>

              <li class= "pull-right"><%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> </li> </br>
              <li class="pull-right"><%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %> </li>

            <% end %>
          </div>
        </ul>




        <%= flash_messages %>


      <%= yield %>
    </div>

  </body>
</html>

app/views/welcome/about.html.erb
<div>
  <h1>Welcome to MADE</h1>
    <p>Maine Ad and Design, the pine tree states cub for creative professionals</p>
</div>

app/views/welcome/index.html.erb
<h1>Welcome to MADE!</h1>
<% if user_signed_in? %>
<h3> Your current plan is <%= current_user.role %> </h3>
    <% if current_user.premium? %>
        <%= link_to "downgrade", downgrade_create_path, class: 'btn btn-success', data: {confirm: 'Are you sure you want to downgrade? Remember, you will have to pay another $15 to get premium features back on your account, and your private wikis will become public.'} %>

    <% else %>
        <%= link_to "upgrade", charges_new_path, class: 'btn btn-success' %>
    <% end %>    
<% else %> 
Sign up today to get invovled in the action!
<% end %>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
    

   <% if current_user.admin? || (current_user.premium? && current_user.id == @wiki.user_id) %>
    <div class="form-group">
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>  
  <% end %>  
    </div>
  </div>  
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis</p>
    <ul>
      <li>Make sure it rhymes.</li>
      <li>Don't use the letter "A".</li>
      <li>The incessant use of hashtags will get you banned.</li>
    </ul>
  </div>
  <div class="col-md-8">
   <%= render partial: 'form', locals: { user: @user } %>
    <%= render partial: 'collaborators/collaborators', locals: { user: @user } %> 
  </div>
</div>

app/views/wikis/index.html.erb
<script>blocmetrics.report('wiki page loaded');</script>

<h1>Wikis</h1>
<div class="row">
   <div class="col-md-8">

         <% @wikis.each do |wiki| %>
             <% unless wiki.private? %>
             <div class="media">
               <div class="media-body">
                 <h4 class="media-heading">
                     <%= link_to wiki.title, wiki %>
                </h4>
              </div>
            </div>
        <% end %>



<% end %>
  </div>
  <div class="col-md-4">

    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
    </div>
</div>

app/views/wikis/new.html.erb
<html>
  <head>
    <title>wikis</title>
    <script>blocmetrics.report('index page loaded');</script>
  </head>



<h1> New Wiki </h1>
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for creating wikis <p>
      <ul>
        <li>make it useful </li>
        <li>make it fun </li>
        <li>make it fierce </li>
      </ul>
    </div>


  <div class="col-md-8">
    <%= render partial: 'form', locals: { user: @user } %>

    </div>
  </div>
</div<

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<div class="row">
  <div class='col-md-8'>
    <h4> Orginally constructed by: <%= @wiki.user.email %> </h4>
    <%= markdown(@wiki.body) %>
  </div>
  <div class= "col-md-4">
    <%= link_to "edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <%= link_to "delete", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this post?'} %>
    
  </div>
</div>